# Podfile
platform :ios, '9.0'
use_frameworks!

install! 'cocoapods',
  :share_schemes_for_development_pods => true


target 'GraphAPI' do
    pod 'RxSwift',    '~> 4.2.0'
    pod 'RxCocoa',    '~> 4.3.1'
    pod 'ADALiOS'
end
