# Podfile
platform :ios, '12.0'
use_frameworks!

install! 'cocoapods',
  :share_schemes_for_development_pods => true


target 'GraphAPI' do
    pod 'RxSwift',    '~> 4.2.0'
    pod 'RxCocoa',    '~> 4.3.1'
    pod 'MSAL', :git => 'https://github.com/AzureAD/microsoft-authentication-library-for-objc', :tag => '0.2.0', :submodules => true
    pod 'ADALiOS'
end
